# Generated by Django 3.1.3 on 2020-11-30 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filmy', '0002_auto_20201130_1345'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='plakat',
            field=models.ImageField(default=None, upload_to='plakaty'),
        ),
    ]
